Create domains
artsiom-kotau/online-store pull request #3
Opened 2021-05-12 12:22 UTC by iryna-karzhova

2021-05-13 13:13 UTC, artsiom-kotau requested changes

2021-05-13 13:13 UTC, artsiom-kotau commented on src/main/java/com/example/onlinestore/domain/Category.java
> +    @JoinColumn(name="good_id", nullable=false)
зачем это поле?

2021-05-13 13:13 UTC, artsiom-kotau commented on src/main/java/com/example/onlinestore/domain/PaymentMethod.java
> +@Table(name = "PAYMENT_METHODS")
Не хватает индивидуальных полей, типа название метода и т.п

2021-05-13 13:13 UTC, artsiom-kotau commented on src/main/java/com/example/onlinestore/domain/Transaction.java
> +public class Transaction {
Транзакция должна быть связана с Good in Bucket

2021-05-13 13:13 UTC, artsiom-kotau commented on src/main/java/com/example/onlinestore/domain/User.java
> +@Entity
username и email добавь хоть какие

2021-05-13 13:13 UTC, artsiom-kotau commented on src/main/java/com/example/onlinestore/domain/Profile.java
> +@Table(name = "PROFILES")
имя юзера хотя бы

2021-05-13 13:13 UTC, artsiom-kotau commented on src/main/resources/db/migration/V1__Init_DB.sql
> +create sequence hibernate_sequence start 1 increment 1;
Зачем этот файл?

2021-05-24 06:26 UTC, closed without merging

2021-05-24 06:26 UTC, iryna-karzhova commented
was changed